### ISSUE TITLE
Program is written in C

### ISSUE THREAD

**Issue by citelao** [evangambit/Gif-Captain#1]
Should be python or a language that makes image manipulation easy...

I.e. does not require templating

**Comment by evangambit** [comment]
Unfortunately, I think speed is still a critical consideration.  A 640x400 gif with 100 frames = 25 million pixels to potentially manipulate, which (on my machine) takes ~4 seconds (in Python) to simply set to to value (let alone 3 values, which presumably scales by at least a factor of 3).  Such an operation is nearly instantaneous in C++.  Also, while the title of this work suggests it is for solely captioning animated gifs, it also serves as a reasonable base for creating them from scratch, for which speed is likely (depending on what one is doing) even more important.

I suppose there isn't much of an argument for not setting the default template of the Image class to Color though.

**Comment by citelao** [comment]
👍
